---
baseURL: "/security/"
languageCode: "en-us"
title: "Product Security Guide"
themesDir: "../themes"
theme: "eximiee"

relativeURLs: false

blackfriday:
  plainIDAnchors: true

params:
  canonicalBasePath: "https://docs.eximeebpms.org"
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Manual"
      url: "/manual"
    - id: "enterprise"
      name: "Enterprise"
      url: "/enterprise"
    - id: "security"
      name: "Security"
      url: "/security"
  section:
    id: "security"
  github:
    repositoryName: "EximeeBPMS"
    branch: "master/security"

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
- taxonomyTerm
...
