---
baseURL: "/manual/latest/"
languageCode: "en-us"
title: "EximeeBPMS documentation "
themesDir: "../../themes"
theme: "eximee"

relativeURLs: false

blackfriday:
  plainIDAnchors: true

params:
  canonicalBasePath: "https://docs.eximeebpms.org"
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Manual"
      url: "/manual/latest"
    - id: "enterprise"
      name: "Enterprise"
      url: "/enterprise"
    - id: "security"
      name: "Security"
      url: "/security"
  section:
    id: "manual"
    version: "latest"
    versionAlias: "latest"
    versions:
      - "latest"
  github:
    repositoryName: "EximeeBPMS/eximeebpms-docs"
    branch: "master/manual"

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
- taxonomyTerm
...
